from django.contrib import admin

from . import models

admin.site.register(models.ReportObjectType)
admin.site.register(models.ReportObject)
admin.site.register(models.Tag)
admin.site.register(models.ReportTagLink)
admin.site.register(models.AtlasUser)
admin.site.register(models.Groups)
admin.site.register(models.UserGroupMemberships)
admin.site.register(models.Initiative)
admin.site.register(models.Term)
admin.site.register(models.Collection)
admin.site.register(models.CollectionReport)
admin.site.register(models.CollectionTerm)
admin.site.register(models.UserPreferences)
admin.site.register(models.UserRoles)
admin.site.register(models.RolePermissions)
admin.site.register(models.RolePermissionLinks)
admin.site.register(models.GroupRoleLinks)
admin.site.register(models.UserRoleLinks)
admin.site.register(models.OrganizationalValue)
admin.site.register(models.EstimatedRunFrequency)
admin.site.register(models.Fragility)
admin.site.register(models.MaintenanceSchedule)
admin.site.register(models.MaintenanceLogStatus)
admin.site.register(models.FragilityTag)
admin.site.register(models.ReportObjectDoc)
admin.site.register(models.ReportObjectDocTerms)
admin.site.register(models.ReportObjectDocFragilityTags)
admin.site.register(models.MaintenanceLog)
admin.site.register(models.ReportObjectDocMaintenanceLogs)
admin.site.register(models.ReportObjectHierarchy)
admin.site.register(models.ReportObjectQuery)
admin.site.register(models.ReportObjectRunData)
admin.site.register(models.ReportObjectRunDataBridge)
admin.site.register(models.UserFavoriteFolders)
